### ISSUE TITLE
Re-try indexing with OpenAI embeddings

### ISSUE THREAD

**Issue by DallanQ** [scripturecentralqa/models#133]
Maybe the OpenAI embeddings produce better search results?  For this task you will need to:

1. cd to the data directory, download the splits from: https://www.dropbox.com/scl/fi/xg5vvhyt20zhqf23plj5d/split.tgz?rlkey=amfa17ibbddo0v0tqx4mvejel&dl=0 and unpack them using `tar -xzvf split.tgz` This will create 17 subdirectories under split. You can ignore the `model` subdirectory.
2. **Make sure** the `.env` file in your models repo contains your **personal** PINECONE_API_KEY and PINECONE_ENV! You want to index this files into your personal pinecone index, not the live production index. Don't start notebook 35_indexer until you have done this.
3. Log into your personal account at pinecone.io and delete the scqa index if it exists.
4.  In notebook 35_indexer, use OpenAI as the embedder by uncommenting the lines to create an embedder from OpenAI and commenting the lines to create an embedder from VoyageAI
5.   Run the 35_indexer notebook for each of the subdirectories under split (except model) to index the files using the OpenAI embeddings. Make sure that the index_stats say that the index contains 0 entries when you run the notebook for the first time. It will take a while to run the notebook for each of the subdirectories.
6.   Install and run the server following the instructions in the README.md file in the server repo. Make sure that your personal PINECONE_API_KEY and PINECONE_ENV values are in the `.env` file in the server repo.
7.   In server.py in the server repo, uncomment the lines around line 150 to get the embedding from OpenAI and comment the line to get the embedding from voyageai
8.   Follow the instructions in the [Experiment Process Explained](https://github.com/orgs/scripturecentralqa/projects/1/views/3?pane=issue&itemId=46403275) task to determine if the OpenAI embeddings are better.

**Comment by VladmirNzeh** [comment]
Sir, Kindly modify the number 7 instruction from server.py to main.py

**Comment by DallanQ** [comment]
OpenAI embeddings improved the NDCG score by 2 points for our use-case.
